name: My Workflow
on:
  push:
    branches:
    - release/v[1-99].[0-9][0-9]
    - release/v[1-99].[0-9]

jobs:
  Deploy_this_ca:
    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest

    steps:
    - name: download repo
      uses: actions/checkout@v3

    - name: check directory
      run: ls -l

    - name: deploy railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "ruthless-spade"

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "GipSA 56 CI/CD Submission",
                  "emoji": true
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* Yap Wei Jie Jeremy"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Email:* jeremy.yap27@gmail.com"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:* A0168106H"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:* https://github.com/${{github.repository}}"
                  }
                ]
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "https://${{vars.RAILWAYURL}}"
                },
                "accessory": {
                  "type": "button",
                  "text": {
                    "type": "plain_text",
                    "text": "Go",
                    "emoji": true
                  },
                  "value": "click_me_123",
                  "url": "https://${{vars.RAILWAYURL}}",
                  "action_id": "button-action"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK