name: My Workflow
on: [push]

jobs:
  Deploy_this_ca:
    runs-on: ubuntu-latest

    steps:
    - name: download repo
      uses: actions/checkout@v3

    - name: check directory
      run: ls -l

    - name: deploy railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "ruthless-spade"

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "You have a new request:"
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:* Yap Wei Jie Jeremy"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*When:*\nSubmitted Aut 10"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Last Update:*\nMar 10, 2015 (3 years, 5 months)"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Last Update:*\nMar 10, 2015 (3 years, 5 months)"
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK