name: My Workflow
on: [push]

jobs:
  Deploy_this_ca:
    runs-on: ubuntu-latest

    steps:
    - name: download repo
      uses: actions/checkout@v3

    - name: check directory
      run: ls -l

    - name: deploy railway
      uses: bervProject/railway-deploy@main
      with:
        railway_token: ${{ secrets.RAILWAY_TOKEN }}
        service: "ruthless-spade"

    - name: Send custom JSON data to Slack workflow
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        # For posting a rich message using Block Kit
        payload: |
          {
            "blocks": [
              {
                "type": "context",
                "elements": [
                  {
                    "type": "plain_text",
                    "text": "*DipSA56 CI/CD Submission*",
                    "emoji": true
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "plain_text",
                    "text": "*Name:* Yap Wei Jie Jeremy",
                    "emoji": true
                  },
                  {
                    "type": "plain_text",
                    "text": "*Email:* jeremy.yap27@gmail.com",
                    "emoji": true
                  }
                ]
              },
              {
                "type": "context",
                "elements": [
                  {
                    "type": "plain_text",
                    "text": "Matriculation: A0168106H",
                    "emoji": true
                  },
                  {
                    "type": "plain_text",
                    "text": "*Repository:* https://github.com/goodalways/DipSA-CICD-56---Jeremy",
                    "emoji": true
                  }
                ]
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK